name: clean_architecture
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  dartz: ^0.10.1
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true